### ISSUE TITLE
canvas.print_rgba() to_unmultiplied_rgba8888() is extremely slow

### ISSUE THREAD

**Issue by jimbo1qaz** [anntzer/mplcairo#12]
```python
assert isinstance(canvas, FigureCanvasCairo):

w = self.cfg.width
h = self.cfg.height
assert (w, h) == canvas.get_width_height()
buffer_rgb = BytesIO()
canvas.print_rgba(buffer_rgb)
```

old name = `mplcairo._util.to_unmultiplied_rgba8888()` (renamed in https://github.com/anntzer/mplcairo/commit/30db91f61cd5449a90045627d80e0e23441db6a6) is singlehandedly slowing my 1280x720 render to 11fps. (9.95 sec out of 11 according to CProfile).

I don't even use the alpha channel (fully opaque).

-------

```
poetry install
  - Installing pycairo (1.18.0)
  - Installing mplcairo (0.1)
```

```
import mplcairo
mplcairo.get_versions()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
AttributeError: module 'mplcairo' has no attribute 'get_versions'
```

Same I `pip install git+https://github.com/anntzer/mplcairo` from Git master.

Ubuntu 18.04

Package: libcairo2
Version: 1.15.10-2

Package: libcairo2-dev
Version: 1.15.10-2

----

[mplcairo slow.zip](https://github.com/anntzer/mplcairo/files/2722020/mplcairo.slow.zip)

**Comment by anntzer** [comment]
Is there a specific reason you need unmultiplied rgba8888 output?  cairo does not provide this mode (https://cairographics.org/manual/cairo-Image-Surfaces.html#cairo-format-t) so I need to convert it manually in any case.
I can try moving the numpy code to C++ but I doubt it would provide a huge gain?

**Comment by anntzer** [comment]
I guess I can special-case the fully-opaque case, though, can you try manually applying
```
diff --git i/lib/mplcairo/_util.py w/lib/mplcairo/_util.py
index ad59370..d0cb0eb 100644
--- i/lib/mplcairo/_util.py
+++ w/lib/mplcairo/_util.py
@@ -18,6 +18,8 @@ def to_straight_rgba8888(buf):
     # The straightening formula is from cairo-png.c.
     rgb = rgba[..., :-1]
     alpha = rgba[..., -1]
+    if alpha.max() == 255:  # Special-case fully-opaque buffers for speed.
+        return rgba
     mask = alpha != 0
     for channel in np.rollaxis(rgb, -1):
         channel[mask] = (
```
and see whether it helps?

**Comment by jimbo1qaz** [comment]
I don't need unmultiplied output, but FigureCanvasCairo.print_rgba() provides that (slowly) and I don't know what to use instead.

I found a much faster way:

```python
buffer_rgb: np.ndarray = canvas.get_renderer()._get_buffer()
buffer_rgb = buffer_rgb.flatten('K')
```

But I don't know if I should be calling private methods.

**Comment by anntzer** [comment]
Oh, I see, there's just no "public" way to get the raw internal buffer right now (I think), thanks for pointing that out.
_get_buffer is your best choice for now, but I'll add a public API for that.

**Comment by jimbo1qaz** [comment]
I noticed that `FigureCanvasAgg.tostring_rgb()` (haven't tested `_argb`) and `FigureCanvasCairo.get_renderer()._get_buffer()` have the same byte order (ffmpeg rgb24/32), while `FigureCanvasCairo.print_rgba(buffer_rgb)` is reversed (ffmpeg bgr32). Maybe byteswapping is causing part of the slowdown?

Before: 11fps
Patched: 46fps
Unconditional return: 48fps
get_renderer()._get_buffer(): 150fps I think?

**Comment by anntzer** [comment]
The fact that byteorder is different in _get_buffer() is expected, and yes the byteswapping in _to_straight_rgba8888 (or even _to_premultiplied_rgba8888) is likely the source of the slowdown according to your profiling at least.

The 8-bit-per-channel native formats of Agg and cairo are what they are and not really configurable.
In Agg the format is RGBA8888 which means that in memory you have the R, G, B, A channels in that order.
In cairo the format is ARGB32 which means that
- on a big-endian machine, in memory the channels are A, R, G, B in that order;
- on a little-endian machine (more common, but perhaps you're on some funny arch?), in memory the channels are B, G, R, A in that order.
_get_buffer() gives you that representation; buffer_rgba() does the byteswapping (in _to_premultiplied_rgba8888).

I don't know what the ffmpeg pixel formats correspond to, you'll have to check by yourself.

-----

Thanks for your feedback.
As noted elsewhere I need to make a new release.  Unfortunately I think I also introduced a performance regression recently so that needs to be investigated first.

**Comment by anntzer** [comment]
I added `mplcairo.get_raw_buffer(canvas)` as a "public" way to get the raw internal buffer.

(It is intentionally not a canvas method as I'd prefer keep the canvas method API as close as possible to Matplotlib upstream.)

**Comment by jimbo1qaz** [comment]
thanks. maybe I'll use the new API once it appears in a release.

**Comment by anntzer** [comment]
Can I close this issue, or is there anything else?
