### ISSUE TITLE
Crash on import

### ISSUE THREAD

**Issue by QuLogic** [anntzer/mplcairo#2]
Not sure what's triggering it as there's not much else printed out:
```
$ PYTHONPATH=/builddir/build/BUILDROOT/python-mplcairo-0.1-0.2.a1.fc29.x86_64/usr/lib64/python3.6/site-packages  /usr/bin/python3 -c 'import mplcairo.base'
terminate called after throwing an instance of 'pybind11::error_already_set'
  what():  SystemError: <built-in method __contains__ of dict object at 0x7f05392dc480> returned a result with an error set
/var/tmp/rpm-tmp.AHgxop: line 33:   311 Aborted                 (core dumped) PYTHONPATH="/builddir/build/BUILDROOT/python-mplcairo-0.1-0.2.a1.fc29.x86_64/usr/lib64/python3.6/site-packages" /usr/bin/python3 -c 'import mplcairo.base'
```
using pybind11 2.2.2, cairo 1.15.12, and python 3.6.5.

**Comment by anntzer** [comment]
HEAD or 0.1?

**Comment by QuLogic** [comment]
0.1a1

**Comment by anntzer** [comment]
Does this also occur on master?

I believe it's an instance of https://github.com/pybind/pybind11/issues/1113.  To figure out what the exception raised is, add a `#include <iostream>` at the top of _mplcairo.cpp and wrap the entire body of PYBIND11_MODULE as follows:
```
PYBIND11_MODULE(mplcairo, m) {
  try {
  <... the original body ...>
  } catch (py::error_already_set& e) {
    std::cout << e.what() << "\n";
  }
}
```

**Comment by QuLogic** [comment]
Ohh, I was dumb; I forgot to include matplotlib in the chroot. It now works as a simple import and for saving a simple figure, also with and without libraqm.

**Comment by anntzer** [comment]
Well, it would still be nice if a missing dependency didn't abort() the interpreter... anyways, I filed a PR upstream to fix the issue.

**Comment by QuLogic** [comment]
I don't normally build off `master` when there's a tag available, so rebasing is not an issue. I currently only need to build with just a small patch to fix the `extern C` thing.

I'm also experimenting with a patch to remove the editable install requirement for testing, but it looks like I'm still getting a few test failures. I know it's not a 100% match, but since you don't run on Travis, I'm not sure what you expect there? Maybe I should just use the infinite tolerance option and treat it as more of a smoke test?

In any case, there's some sort of issue with the latest Qt5 build, so my package review is still stalled for the moment.

**Comment by anntzer** [comment]
Yup, the intent right now is to just run with --infinite-tolerance and manually check the results -- essentially because I don't have a good solution for the "infinite test images repo bloat" problem (which is probably even worse in my case because I am not certain *cairo*'s output is pixel consistent either... (in a sense we have it "easy" in matplotlib because we have effectively pinned our renderer (agg).)

I can probably just generate a tarball of manually validated test images built against a fixed version of freetype and cairo if that helps, or do you prefer that I figure out a high enough (but not infinite) tolerance that makes tests pass with Matplotlib's own baseline images?  (no guarantees on the schedule though)

**Comment by QuLogic** [comment]
Well, we already have a tarball of test images (two in fact because 28 and 29 use different FT versions) for Matplotlib itself. I think if things aren't stable, there's no point in bogging things down with yet another tarball of images. A rough number smaller than infinity might be nice though.

For the editable thing, I use [this](https://github.com/QuLogic/mplcairo/tree/fedora-patches).

**Comment by QuLogic** [comment]
Oh yea, as far as headers go, there's no network on builders, so downloading headers wouldn't work. I'll just need to ping the maintainer to build the new libraqm (they've already merged my patch to update it.)

**Comment by anntzer** [comment]
Thanks, I included the patch for running the tests (didn't know about `--pyargs`, good thing to learn).

**Comment by anntzer** [comment]
Pushed some machinery that sorts the tests by rms failure (thanks for nudging me in that direction :-)), which allowed me to find that there is a real bug regarding dpi handling of raster images embedded in vector format outputs, which needs to be fixed before the next tag, and get some idea of what tolerance to use (for your purpose, you should just skip all mathtext and tight-layout tests, because the change in text rendering and bboxes lead to things being rendered at "completely" different positions and thus huge rmses which are pretty meaningless, and the other tests should pass at 30 or 60 depending on what other tests (those that are "somewhat" dependent on autolayouting) that I also exclude).
